import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Sidebar from "./components/layout/Sidebar"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider >
          <div className="h-screen bg-black">
            <div className="container h-full mx-auto xl:px-30 max-w-6xl ">
              <div className="grid grid-cols-4 h-full">
              
              <Sidebar />
                <div className="
                col-span-3
                lg:col-span-2
                border-x-[1px]
                border-neutral-800 
                ">  
                  {children}

                </div>
              </div>
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
